name: unsplash_getx
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  http: ^0.13.3
  logger: ^2.1.0
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_staggered_grid_view: ^0.7.0
  iconsax: ^0.0.8
  image_gallery_saver: '^2.0.3'
  dio: ^5.4.1
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.4
  path_provider: ^2.1.2
  http_interceptor: ^1.0.2
  share_plus: ^7.2.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

